// Generated by CoffeeScript 1.4.0

(function(window, document) {
  "use strict";

  /*
      Default configuration for detectr
  */

  var defaultTests, detectCache, detectResultCache, detectr, globalOptions, runTest;
  defaultTests = {
    tests: {
      desktop: {
        run: function() {
          return !runTest('mobile');
        },
        result: 'desktop'
      },
      mobile: {
        run: function() {
          return runTest('android') || runTest('ios') || runTest('bada') || runTest('webos') || runTest('wp7') || runTest('blackberry');
        },
        result: 'mobile'
      },
      macosx: {
        run: function() {
          return ~detectr.Browser.platform.name().indexOf('macosx');
        },
        result: 'macosx'
      },
      linux: {
        run: function() {
          return ~detectr.Browser.platform.name().indexOf('linux');
        },
        result: 'linux'
      },
      windows: {
        run: function() {
          return ~detectr.Browser.platform.name().indexOf('windows');
        },
        result: 'windows'
      },
      android: {
        run: function() {
          return detectr.Browser.get().match(/Android/);
        },
        result: 'android'
      },
      ios: {
        run: function() {
          return runTest('ipod') || runTest('iphone') || runTest('ipad');
        },
        result: 'ios'
      },
      ipod: {
        run: function() {
          return detectr.Browser.get().match(/iPod/);
        },
        result: 'ipod'
      },
      iphone: {
        run: function() {
          return detectr.Browser.get().match(/iPhone/);
        },
        result: 'iphone'
      },
      ipad: {
        run: function() {
          return detectr.Browser.get().match(/iPad/);
        },
        result: 'ipad'
      },
      bada: {
        run: function() {
          return detectr.Browser.get().match(/Bada/);
        },
        result: 'bada'
      },
      webos: {
        run: function() {
          return detectr.Browser.get().match(/webOS/);
        },
        result: 'webos'
      },
      wp7: {
        run: function() {
          return detectr.Browser.get().match(/Windows Phone OS/);
        },
        result: 'wp7'
      },
      blackberry: {
        run: function() {
          return detectr.Browser.get().match(/RIM/);
        },
        result: 'blackberry'
      },
      landscape: {
        run: function() {
          return detectr.Display.width() >= detectr.Display.height();
        },
        result: 'landscape'
      },
      portrait: {
        run: function() {
          return !runTest('landscape');
        },
        result: 'portrait'
      },
      'browser-chrome': {
        run: function() {
          return detectr.Browser.get().match(/Chrome/);
        },
        result: 'browser-chrome'
      },
      'browser-firefox': {
        run: function() {
          return detectr.Browser.get().match(/Firefox/);
        },
        result: 'browser-firefox'
      },
      'browser-ie': {
        run: function() {
          return detectr.Browser.get().match(/MSIE/);
        },
        result: 'browser-ie'
      },
      'browser-safari': {
        run: function() {
          return detectr.Browser.get().match(/Safari/) && !detectr.Browser.get().match(/Chrome/);
        },
        result: 'browser-safari'
      },
      'browser-opera': {
        run: function() {
          return detectr.Browser.get().match(/Opera/);
        },
        result: 'browser-opera'
      }
    }
  };
  detectCache = {};
  detectResultCache = {};
  globalOptions = {};
  /*
      Runs a defined test
  */

  runTest = function(testName, testObject) {
    var htmlClassName, testResultBool, testResultString;
    if (!testName) {
      return void 0;
    }
    if (detectCache[testName]) {
      return detectCache[testName];
    }
    if (!testObject) {
      return void 0;
    }
    if (testObject.run) {
      if (testObject.run) {
        testResultBool = !!testObject.run();
      }
      testResultString = testObject.result;
    }
    if ((globalOptions != null ? globalOptions.debug : void 0) != null) {
      console.log("Testing " + testName + ": Result: " + testResultBool);
    }
    detectCache[testName] = testResultBool;
    if (testResultBool) {
      htmlClassName = document.documentElement.className;
      htmlClassName += " " + testResultString;
      htmlClassName = htmlClassName.trim();
      document.documentElement.className = htmlClassName;
      return detectResultCache[testName] = testResultString;
    }
  };
  /*
      detectr constructor
  */

  detectr = function(config, options) {
    var key, parsedPlatform, value, _ref;
    if (!(config && config.tests)) {
      return void 0;
    }
    globalOptions = options;
    parsedPlatform = navigator.userAgent.match(/(.*?)\s(.*?)\((.*?);\s(.*?)\)/);
    detectr.Browser || (detectr.Browser = {
      get: function() {
        return navigator.userAgent;
      },
      name: function() {
        return navigator.appName;
      },
      version: function() {
        return navigator.appVersion;
      },
      platform: {
        name: function() {
          return parsedPlatform[4].replace(/\s/gi, '').toLowerCase();
        },
        original: function() {
          return navigator.platform;
        }
      },
      language: function() {
        var language;
        language = navigator.language || navigator.systemLanguage;
        if (language != null) {
          return language.split('-')[0];
        }
      }
    });
    detectr.Display || (detectr.Display = {
      width: function() {
        return window.innerWidth;
      },
      height: function() {
        return window.innerHeight;
      }
    });
    detectr.clear();
    _ref = config.tests;
    for (key in _ref) {
      value = _ref[key];
      detectr.add(key, value);
    }
    detectr.Display.orientation = detectResultCache['landscape'] || detectResultCache['portrait'];
    return detectr;
  };
  /*
      Checks for a test and returns a boolean value
  */

  detectr.is = function(value) {
    var result;
    if (!value) {
      return void 0;
    }
    value = value.replace(/\s/gi, '').toLowerCase();
    if (detectCache[value]) {
      return result = detectCache[value];
    }
  };
  /*
      Checks for a test and returns the result value of the test
  */

  detectr.result = function(value) {
    var result;
    if (!value) {
      return void 0;
    }
    value = value.replace(/\s/gi, '').toLowerCase();
    if (detectResultCache[value]) {
      return result = detectResultCache[value];
    }
  };
  /*
      Clear cache
  */

  detectr.clear = function() {
    var htmlClassName, key, value;
    detectCache = {};
    for (key in detectResultCache) {
      value = detectResultCache[key];
      htmlClassName = document.documentElement.className;
      htmlClassName = htmlClassName.replace(value, '').trim();
      document.documentElement.className = htmlClassName;
    }
    detectResultCache = {};
    return detectr;
  };
  /*
      Remove a test
  */

  detectr.remove = function(testName) {
    var htmlClassName;
    if (detectCache[testName]) {
      delete detectCache[testName];
    }
    if (detectResultCache[testName]) {
      htmlClassName = document.documentElement.className;
      htmlClassName = htmlClassName.replace(detectResultCache[testName], '').replace(/^\s+|\s+$/g, '').replace(/\s+/g, ' ');
      document.documentElement.className = htmlClassName;
      delete detectResultCache[testName];
    }
    return detectr;
  };
  /*
      Add a test
  */

  detectr.add = function(testName, testObject) {
    var key, value;
    if (testName.tests) {
      for (key in testName) {
        value = testName[key];
        detectr.add(key, value);
      }
    } else {
      runTest(testName, testObject);
    }
    return detectr;
  };
  /*
      Expose defaultTests for those who need re-execute the detectr function
  */

  detectr.defaultTests = defaultTests;
  /*
      Call detectr constructor with default configuration
      and set the reference to the detectr object
  */

  return window.detectr = detectr(defaultTests);
})(this, document);
